/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.xemacscode.demo;

import java.awt.Color;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Seling extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    Object[] data = new Object[0];

    public Seling() {
        initComponents();
        model = (DefaultTableModel) tb_Product.getModel();
        showData();
        GetCat();
    }
    private JFrame frame;
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    public void clearRow() {
        int row = model.getRowCount() - 1;
        while (row > -1) {
            model.removeRow(row);
            row--;
        }
    }

    public void showData() {
        clearRow();
        try {
            Connection Con = DBConnection.connectDB();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from PRODUCTB");
            int row = 0;
            while (Rs.next()) {
                model.addRow(data);
                model.setValueAt(Rs.getString(1), row, 0);
                model.setValueAt(Rs.getString(2), row, 1);
                model.setValueAt(Rs.getString(3), row, 2);
                model.setValueAt(Rs.getString(4), row, 3);
                
                row++;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearTextBox() {
        //txt_ProdId.setText("");
        txt_prodName.setText("");
        txt_Quanlt.setText("");
        cb_Cate.setSelectedIndex(0);
    }
    int Prid, newQty;


    private void GetCat() {
        try {
            Connection Con = DBConnection.connectDB();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from CATEGORYTB");

            while (Rs.next()) {
                String Mycat = Rs.getString("CATNAME");
                cb_Cate.addItem(Mycat);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_prodName = new javax.swing.JTextField();
        cb_Cate = new javax.swing.JComboBox<>();
        bt_Add = new javax.swing.JButton();
        bt_Edit = new javax.swing.JButton();
        bt_Re = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Product = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_Quanlt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Bill = new javax.swing.JTextArea();
        bt_Clear1 = new javax.swing.JButton();
        Grdtotalbl = new javax.swing.JLabel();
        bt_Re1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NAME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("QUANTITY");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("CATEGORY");

        txt_prodName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_prodName.setForeground(new java.awt.Color(0, 51, 102));
        txt_prodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_prodNameKeyReleased(evt);
            }
        });

        cb_Cate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_Cate.setForeground(new java.awt.Color(0, 51, 102));
        cb_Cate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_CateItemStateChanged(evt);
            }
        });
        cb_Cate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_CateMouseClicked(evt);
            }
        });
        cb_Cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CateActionPerformed(evt);
            }
        });

        bt_Add.setBackground(new java.awt.Color(204, 255, 255));
        bt_Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_Add.setText("Add to Bill");
        bt_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AddMouseClicked(evt);
            }
        });

        bt_Edit.setBackground(new java.awt.Color(204, 204, 255));
        bt_Edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_Edit.setText("Print");
        bt_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_EditMouseClicked(evt);
            }
        });

        bt_Re.setBackground(new java.awt.Color(255, 255, 204));
        bt_Re.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_Re.setText("Filter");
        bt_Re.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ReMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("MANAGE PRODUCTS");

        tb_Product.setBackground(new java.awt.Color(153, 204, 255));
        tb_Product.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductID", "NAME", "PRICE", "CATEGORY"
            }
        ));
        tb_Product.setRowHeight(25);
        tb_Product.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tb_Product.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tb_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Product);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("PRODUCTS LIST");

        txt_Quanlt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Quanlt.setForeground(new java.awt.Color(0, 51, 102));
        txt_Quanlt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_QuanltKeyReleased(evt);
            }
        });

        txt_Bill.setColumns(20);
        txt_Bill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Bill.setRows(5);
        jScrollPane2.setViewportView(txt_Bill);

        bt_Clear1.setBackground(new java.awt.Color(255, 255, 204));
        bt_Clear1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_Clear1.setText("Clear");
        bt_Clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Clear1MouseClicked(evt);
            }
        });

        Grdtotalbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Grdtotalbl.setForeground(new java.awt.Color(0, 51, 51));
        Grdtotalbl.setText("Rs");

        bt_Re1.setBackground(new java.awt.Color(255, 255, 204));
        bt_Re1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_Re1.setText("Refresh");
        bt_Re1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Re1MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/online-shop.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/credit-card.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atm.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(29, 29, 29)
                                        .addComponent(txt_Quanlt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(txt_prodName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_Add)
                                .addGap(28, 28, 28)
                                .addComponent(bt_Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Cate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Re)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Re1)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Grdtotalbl)
                                        .addGap(274, 274, 274))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_Cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(bt_Re)
                            .addComponent(bt_Re1)
                            .addComponent(txt_prodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Quanlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_Add)
                            .addComponent(bt_Clear1))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Grdtotalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addComponent(bt_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(90, 90, 90))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/x-mark-5-32.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shutdown.png"))); // NOI18N
        jLabel10.setText("LOGOUT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sale-tag.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(237, 237, 237))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_prodNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prodNameKeyReleased
        //lb_Name.setText("");
    }//GEN-LAST:event_txt_prodNameKeyReleased

    private void cb_CateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CateActionPerformed
    int i = 0;
    private void bt_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AddMouseClicked
        if (txt_prodName.getText().trim().isEmpty() && txt_Quanlt.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Missing Information");

        
        } else {
            i++;
            ProdTot = Uprice * Integer.valueOf(txt_Quanlt.getText());
            GrdTotal = GrdTotal + ProdTot;
            if (i == 1) {
                txt_Bill.setText(txt_Bill.getText() + "    ============BUDU WANCHAM POINT============\n" + "          NUM     PRODUCT     PRICE     QUANTITY     TOTAL\n          "
                        + i + "       " + txt_prodName.getText() + "        " + Uprice + "           " + txt_Quanlt.getText() + "              " + ProdTot + "\n          ");
            } else {
                txt_Bill.setText(txt_Bill.getText() + i
                        + "       " + txt_prodName.getText()
                        + "        " + Uprice
                        + "           " + txt_Quanlt.getText()
                        + "              " + ProdTot + "\n          ");
            }
            Grdtotalbl.setText("RS " + GrdTotal);

        }
    }//GEN-LAST:event_bt_AddMouseClicked

    private void bt_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EditMouseClicked
        try {
            txt_Bill.print();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_bt_EditMouseClicked

    private void bt_ReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReMouseClicked

        String prodcate = cb_Cate.getSelectedItem().toString();
        try {
            Connection Con = DBConnection.connectDB();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from CATEGORYTB where CATNAME='" + prodcate + "' ");

           int row = 0;
            while (Rs.next()) {
                
            }

            // showData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_ReMouseClicked
    Double Uprice, ProdTot = 0.0, GrdTotal = 0.0;
    int AvailQty;
    private void tb_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ProductMouseClicked
        int select = tb_Product.getSelectedRow();
        Prid = Integer.valueOf(model.getValueAt(select, 0).toString());
       
        txt_prodName.setText(tb_Product.getValueAt(select, 1).toString());
        Uprice = Double.valueOf(model.getValueAt(select, 2).toString());


    }//GEN-LAST:event_tb_ProductMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txt_QuanltKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_QuanltKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuanltKeyReleased

    private void bt_Clear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Clear1MouseClicked
        clearTextBox();
    }//GEN-LAST:event_bt_Clear1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if (JOptionPane.showConfirmDialog(frame, "You want to Logout?", "POS",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void cb_CateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_CateMouseClicked

    }//GEN-LAST:event_cb_CateMouseClicked

    private void bt_Re1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Re1MouseClicked
        showData();
        clearTextBox();
    }//GEN-LAST:event_bt_Re1MouseClicked

    private void cb_CateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_CateItemStateChanged
        /*String prodcate = cb_Cate.getSelectedItem().toString();
        try {
            Connection Con = DBConnection.connectDB();
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from CATEGORYTB where CATNAME='" + prodcate + "' ");

            showData();

            // showData();
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cb_CateItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grdtotalbl;
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_Clear1;
    private javax.swing.JButton bt_Edit;
    private javax.swing.JButton bt_Re;
    private javax.swing.JButton bt_Re1;
    private javax.swing.JComboBox<String> cb_Cate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_Product;
    private javax.swing.JTextArea txt_Bill;
    private javax.swing.JTextField txt_Quanlt;
    private javax.swing.JTextField txt_prodName;
    // End of variables declaration//GEN-END:variables
}
